const pokemons = [
{ id: "001", nome: "Bulbasaur", tipo: ["Planta","Veneno"], descricao: "Carrega uma semente nas costas.", favorito: false },
{ id: "002", nome: "Ivysaur", tipo: ["Planta","Veneno"], descricao: "A semente cresce com energia solar.", favorito: false },
{ id: "003", nome: "Venusaur", tipo: ["Planta","Veneno"], descricao: "Flor grande que absorve luz solar.", favorito: false },
{ id: "004", nome: "Charmander", tipo: ["Fogo"], descricao: "Chama na cauda indica sua vida.", favorito: false },
{ id: "005", nome: "Charmeleon", tipo: ["Fogo"], descricao: "Temperamento agressivo.", favorito: false },
{ id: "006", nome: "Charizard", tipo: ["Fogo","Voador"], descricao: "Cospe fogo intenso.", favorito: false },
{ id: "007", nome: "Squirtle", tipo: ["Agua"], descricao: "Ataca com jatos de água.", favorito: false },
{ id: "008", nome: "Wartortle", tipo: ["Agua"], descricao: "Cauda simboliza longevidade.", favorito: false },
{ id: "009", nome: "Blastoise", tipo: ["Agua"], descricao: "Canhões de água no casco.", favorito: false },
{ id: "010", nome: "Caterpie", tipo: ["Inseto"], descricao: "Evolui rapidamente.", favorito: false },
{ id: "011", nome: "Metapod", tipo: ["Inseto"], descricao: "Fica endurecendo o casulo.", favorito: false },
{ id: "012", nome: "Butterfree", tipo: ["Inseto","Voador"], descricao: "Espalha pólen tóxico.", favorito: false },
{ id: "013", nome: "Weedle", tipo: ["Inseto","Veneno"], descricao: "Possui ferrão venenoso.", favorito: false },
{ id: "014", nome: "Kakuna", tipo: ["Inseto","Veneno"], descricao: "Quase não se move.", favorito: false },
{ id: "015", nome: "Beedrill", tipo: ["Inseto","Veneno"], descricao: "Ataca com ferrões.", favorito: false },
{ id: "016", nome: "Pidgey", tipo: ["Normal","Voador"], descricao: "Ave comum.", favorito: false },
{ id: "017", nome: "Pidgeotto", tipo: ["Normal","Voador"], descricao: "Mais veloz.", favorito: false },
{ id: "018", nome: "Pidgeot", tipo: ["Normal","Voador"], descricao: "Voa em alta velocidade.", favorito: false },
{ id: "019", nome: "Rattata", tipo: ["Normal"], descricao: "Rato ágil.", favorito: false },
{ id: "020", nome: "Raticate", tipo: ["Normal"], descricao: "Dentes fortes.", favorito: false },
{ id: "021", nome: "Spearow", tipo: ["Normal","Voador"], descricao: "Pequeno e agressivo.", favorito: false },
{ id: "022", nome: "Fearow", tipo: ["Normal","Voador"], descricao: "Bico longo.", favorito: false },
{ id: "023", nome: "Ekans", tipo: ["Veneno"], descricao: "Cobra silenciosa.", favorito: false },
{ id: "024", nome: "Arbok", tipo: ["Veneno"], descricao: "Padrões assustadores.", favorito: false },
{ id: "025", nome: "Pikachu", tipo: ["Eletrico"], descricao: "Armazena eletricidade.", favorito: false },
{ id: "026", nome: "Raichu", tipo: ["Eletrico"], descricao: "Descargas fortes.", favorito: false },
{ id: "027", nome: "Sandshrew", tipo: ["Terra"], descricao: "Corpo resistente.", favorito: false },
{ id: "028", nome: "Sandslash", tipo: ["Terra"], descricao: "Garras afiadas.", favorito: false },
{ id: "029", nome: "Nidoran♀", tipo: ["Veneno"], descricao: "Pequena e cautelosa.", favorito: false },
{ id: "030", nome: "Nidorina", tipo: ["Veneno"], descricao: "Mais protetora.", favorito: false },
{ id: "031", nome: "Nidoqueen", tipo: ["Veneno","Terra"], descricao: "Muito resistente.", favorito: false },
{ id: "032", nome: "Nidoran♂", tipo: ["Veneno"], descricao: "Agressivo.", favorito: false },
{ id: "033", nome: "Nidorino", tipo: ["Veneno"], descricao: "Usa chifre para atacar.", favorito: false },
{ id: "034", nome: "Nidoking", tipo: ["Veneno","Terra"], descricao: "Extremamente forte.", favorito: false },
{ id: "035", nome: "Clefairy", tipo: ["Fada"], descricao: "Ligado à lua.", favorito: false },
{ id: "036", nome: "Clefable", tipo: ["Fada"], descricao: "Raro e sensível.", favorito: false },
{ id: "037", nome: "Vulpix", tipo: ["Fogo"], descricao: "Possui várias caudas.", favorito: false },
{ id: "038", nome: "Ninetales", tipo: ["Fogo"], descricao: "Muito sábio.", favorito: false },
{ id: "039", nome: "Jigglypuff", tipo: ["Normal","Fada"], descricao: "Canta para dormir.", favorito: false },
{ id: "040", nome: "Wigglytuff", tipo: ["Normal","Fada"], descricao: "Corpo macio.", favorito: false },
{ id: "041", nome: "Zubat", tipo: ["Veneno","Voador"], descricao: "Vive em cavernas.", favorito: false },
{ id: "042", nome: "Golbat", tipo: ["Veneno","Voador"], descricao: "Suga energia.", favorito: false },
{ id: "043", nome: "Oddish", tipo: ["Planta","Veneno"], descricao: "Planta noturna.", favorito: false },
{ id: "044", nome: "Gloom", tipo: ["Planta","Veneno"], descricao: "Cheiro forte.", favorito: false },
{ id: "045", nome: "Vileplume", tipo: ["Planta","Veneno"], descricao: "Flor gigante.", favorito: false },
{ id: "046", nome: "Paras", tipo: ["Inseto","Planta"], descricao: "Controlado por fungo.", favorito: false },
{ id: "047", nome: "Parasect", tipo: ["Inseto","Planta"], descricao: "Fungo domina o corpo.", favorito: false },
{ id: "048", nome: "Venonat", tipo: ["Inseto","Veneno"], descricao: "Olhos grandes.", favorito: false },
{ id: "049", nome: "Venomoth", tipo: ["Inseto","Veneno"], descricao: "Asas com pó venenoso.", favorito: false },
{ id: "050", nome: "Diglett", tipo: ["Terra"], descricao: "Vive no subsolo.", favorito: false },
{ id: "051", nome: "Dugtrio", tipo: ["Terra"], descricao: "Três Diglett unidos.", favorito: false },
{ id: "052", nome: "Meowth", tipo: ["Normal"], descricao: "Gosta de moedas.", favorito: false },
{ id: "053", nome: "Persian", tipo: ["Normal"], descricao: "Elegante e ágil.", favorito: false },
{ id: "054", nome: "Psyduck", tipo: ["Agua"], descricao: "Sempre com dor de cabeça.", favorito: false },
{ id: "055", nome: "Golduck", tipo: ["Agua"], descricao: "Nada com velocidade.", favorito: false },
{ id: "056", nome: "Mankey", tipo: ["Lutador"], descricao: "Extremamente irritado.", favorito: false },
{ id: "057", nome: "Primeape", tipo: ["Lutador"], descricao: "Vive com raiva constante.", favorito: false },
{ id: "058", nome: "Growlithe", tipo: ["Fogo"], descricao: "Leal e corajoso.", favorito: false },
{ id: "059", nome: "Arcanine", tipo: ["Fogo"], descricao: "Muito veloz e nobre.", favorito: false },
{ id: "060", nome: "Poliwag", tipo: ["Agua"], descricao: "Espiral na barriga.", favorito: false },
{ id: "061", nome: "Poliwhirl", tipo: ["Agua"], descricao: "Melhor nadador.", favorito: false },
{ id: "062", nome: "Poliwrath", tipo: ["Agua","Lutador"], descricao: "Muito forte.", favorito: false },
{ id: "063", nome: "Abra", tipo: ["Psiquico"], descricao: "Usa teleporte.", favorito: false },
{ id: "064", nome: "Kadabra", tipo: ["Psiquico"], descricao: "Possui poderes mentais.", favorito: false },
{ id: "065", nome: "Alakazam", tipo: ["Psiquico"], descricao: "QI extremamente alto.", favorito: false },
{ id: "066", nome: "Machop", tipo: ["Lutador"], descricao: "Treina constantemente.", favorito: false },
{ id: "067", nome: "Machoke", tipo: ["Lutador"], descricao: "Força incrível.", favorito: false },
{ id: "068", nome: "Machamp", tipo: ["Lutador"], descricao: "Quatro braços poderosos.", favorito: false },
{ id: "069", nome: "Bellsprout", tipo: ["Planta","Veneno"], descricao: "Corpo flexível.", favorito: false },
{ id: "070", nome: "Weepinbell", tipo: ["Planta","Veneno"], descricao: "Atrai presas.", favorito: false },
{ id: "071", nome: "Victreebel", tipo: ["Planta","Veneno"], descricao: "Engole presas.", favorito: false },
{ id: "072", nome: "Tentacool", tipo: ["Agua","Veneno"], descricao: "Flutua nos mares.", favorito: false },
{ id: "073", nome: "Tentacruel", tipo: ["Agua","Veneno"], descricao: "Tentáculos longos.", favorito: false },
{ id: "074", nome: "Geodude", tipo: ["Pedra","Terra"], descricao: "Corpo rochoso.", favorito: false },
{ id: "075", nome: "Graveler", tipo: ["Pedra","Terra"], descricao: "Rola montanhas.", favorito: false },
{ id: "076", nome: "Golem", tipo: ["Pedra","Terra"], descricao: "Casco extremamente duro.", favorito: false },
{ id: "077", nome: "Ponyta", tipo: ["Fogo"], descricao: "Crina em chamas.", favorito: false },
{ id: "078", nome: "Rapidash", tipo: ["Fogo"], descricao: "Corre muito rápido.", favorito: false },
{ id: "079", nome: "Slowpoke", tipo: ["Agua","Psiquico"], descricao: "Muito lento.", favorito: false },
{ id: "080", nome: "Slowbro", tipo: ["Agua","Psiquico"], descricao: "Ligado a um Shellder.", favorito: false },
{ id: "081", nome: "Magnemite", tipo: ["Eletrico","Aco"], descricao: "Flutua com magnetismo.", favorito: false },
{ id: "082", nome: "Magneton", tipo: ["Eletrico","Aco"], descricao: "Três Magnemite unidos.", favorito: false },
{ id: "083", nome: "Farfetch'd", tipo: ["Normal","Voador"], descricao: "Carrega alho-poró.", favorito: false },
{ id: "084", nome: "Doduo", tipo: ["Normal","Voador"], descricao: "Duas cabeças.", favorito: false },
{ id: "085", nome: "Dodrio", tipo: ["Normal","Voador"], descricao: "Três cabeças rápidas.", favorito: false },
{ id: "086", nome: "Seel", tipo: ["Agua"], descricao: "Gosta de frio.", favorito: false },
{ id: "087", nome: "Dewgong", tipo: ["Agua","Gelo"], descricao: "Nada em águas geladas.", favorito: false },
{ id: "088", nome: "Grimer", tipo: ["Veneno"], descricao: "Feito de lodo.", favorito: false },
{ id: "089", nome: "Muk", tipo: ["Veneno"], descricao: "Muito tóxico.", favorito: false },
{ id: "090", nome: "Shellder", tipo: ["Agua"], descricao: "Protegido por concha.", favorito: false },
{ id: "091", nome: "Cloyster", tipo: ["Agua","Gelo"], descricao: "Casco muito duro.", favorito: false },
{ id: "092", nome: "Gastly", tipo: ["Fantasma","Veneno"], descricao: "Corpo gasoso.", favorito: false },
{ id: "093", nome: "Haunter", tipo: ["Fantasma","Veneno"], descricao: "Assusta pessoas.", favorito: false },
{ id: "094", nome: "Gengar", tipo: ["Fantasma","Veneno"], descricao: "Se esconde nas sombras.", favorito: false },
{ id: "095", nome: "Onix", tipo: ["Pedra","Terra"], descricao: "Corpo de pedra gigante.", favorito: false },
{ id: "096", nome: "Drowzee", tipo: ["Psiquico"], descricao: "Come sonhos.", favorito: false },
{ id: "097", nome: "Hypno", tipo: ["Psiquico"], descricao: "Hipnotiza inimigos.", favorito: false },
{ id: "098", nome: "Krabby", tipo: ["Agua"], descricao: "Pinças fortes.", favorito: false },
{ id: "099", nome: "Kingler", tipo: ["Agua"], descricao: "Uma pinça gigante.", favorito: false },
{ id: "100", nome: "Voltorb", tipo: ["Eletrico"], descricao: "Explode facilmente.", favorito: false },
{ id: "101", nome: "Electrode", tipo: ["Eletrico"], descricao: "Explode com muita energia.", favorito: false },
{ id: "102", nome: "Exeggcute", tipo: ["Planta","Psiquico"], descricao: "Conjunto de ovos vivos.", favorito: false },
{ id: "103", nome: "Exeggutor", tipo: ["Planta","Psiquico"], descricao: "Árvore com várias cabeças.", favorito: false },
{ id: "104", nome: "Cubone", tipo: ["Terra"], descricao: "Usa crânio como capacete.", favorito: false },
{ id: "105", nome: "Marowak", tipo: ["Terra"], descricao: "Habilidoso com ossos.", favorito: false },
{ id: "106", nome: "Hitmonlee", tipo: ["Lutador"], descricao: "Chutes extremamente fortes.", favorito: false },
{ id: "107", nome: "Hitmonchan", tipo: ["Lutador"], descricao: "Especialista em socos.", favorito: false },
{ id: "108", nome: "Lickitung", tipo: ["Normal"], descricao: "Língua muito longa.", favorito: false },
{ id: "109", nome: "Koffing", tipo: ["Veneno"], descricao: "Libera gases tóxicos.", favorito: false },
{ id: "110", nome: "Weezing", tipo: ["Veneno"], descricao: "Duas cabeças tóxicas.", favorito: false },
{ id: "111", nome: "Rhyhorn", tipo: ["Terra","Pedra"], descricao: "Muito resistente.", favorito: false },
{ id: "112", nome: "Rhydon", tipo: ["Terra","Pedra"], descricao: "Mais forte e pesado.", favorito: false },
{ id: "113", nome: "Chansey", tipo: ["Normal"], descricao: "Muito gentil.", favorito: false },
{ id: "114", nome: "Tangela", tipo: ["Planta"], descricao: "Coberto por vinhas.", favorito: false },
{ id: "115", nome: "Kangaskhan", tipo: ["Normal"], descricao: "Carrega seu filhote.", favorito: false },
{ id: "116", nome: "Horsea", tipo: ["Agua"], descricao: "Pequeno cavalo-marinho.", favorito: false },
{ id: "117", nome: "Seadra", tipo: ["Agua"], descricao: "Nada com elegância.", favorito: false },
{ id: "118", nome: "Goldeen", tipo: ["Agua"], descricao: "Peixe gracioso.", favorito: false },
{ id: "119", nome: "Seaking", tipo: ["Agua"], descricao: "Chifre poderoso.", favorito: false },
{ id: "120", nome: "Staryu", tipo: ["Agua"], descricao: "Forma de estrela.", favorito: false },
{ id: "121", nome: "Starmie", tipo: ["Agua","Psiquico"], descricao: "Centro brilhante.", favorito: false },
{ id: "122", nome: "Mr. Mime", tipo: ["Psiquico","Fada"], descricao: "Especialista em mímica.", favorito: false },
{ id: "123", nome: "Scyther", tipo: ["Inseto","Voador"], descricao: "Lâminas afiadas.", favorito: false },
{ id: "124", nome: "Jynx", tipo: ["Gelo","Psiquico"], descricao: "Dança misteriosa.", favorito: false },
{ id: "125", nome: "Electabuzz", tipo: ["Eletrico"], descricao: "Gera eletricidade.", favorito: false },
{ id: "126", nome: "Magmar", tipo: ["Fogo"], descricao: "Corpo quente.", favorito: false },
{ id: "127", nome: "Pinsir", tipo: ["Inseto"], descricao: "Chifres fortes.", favorito: false },
{ id: "128", nome: "Tauros", tipo: ["Normal"], descricao: "Muito agressivo.", favorito: false },
{ id: "129", nome: "Magikarp", tipo: ["Agua"], descricao: "Fraco, mas resistente.", favorito: false },
{ id: "130", nome: "Gyarados", tipo: ["Agua","Voador"], descricao: "Extremamente destrutivo.", favorito: false },
{ id: "131", nome: "Lapras", tipo: ["Agua","Gelo"], descricao: "Gentil e inteligente.", favorito: false },
{ id: "132", nome: "Ditto", tipo: ["Normal"], descricao: "Se transforma em qualquer coisa.", favorito: false },
{ id: "133", nome: "Eevee", tipo: ["Normal"], descricao: "Evoluções variadas.", favorito: false },
{ id: "134", nome: "Vaporeon", tipo: ["Agua"], descricao: "Controle sobre água.", favorito: false },
{ id: "135", nome: "Jolteon", tipo: ["Eletrico"], descricao: "Velocidade elétrica.", favorito: false },
{ id: "136", nome: "Flareon", tipo: ["Fogo"], descricao: "Calor intenso.", favorito: false },
{ id: "137", nome: "Porygon", tipo: ["Normal"], descricao: "Pokémon digital.", favorito: false },
{ id: "138", nome: "Omanyte", tipo: ["Pedra","Agua"], descricao: "Fóssil revivido.", favorito: false },
{ id: "139", nome: "Omastar", tipo: ["Pedra","Agua"], descricao: "Predador antigo.", favorito: false },
{ id: "140", nome: "Kabuto", tipo: ["Pedra","Agua"], descricao: "Fóssil raro.", favorito: false },
{ id: "141", nome: "Kabutops", tipo: ["Pedra","Agua"], descricao: "Lâminas afiadas.", favorito: false },
{ id: "142", nome: "Aerodactyl", tipo: ["Pedra","Voador"], descricao: "Dinossauro voador.", favorito: false },
{ id: "143", nome: "Snorlax", tipo: ["Normal"], descricao: "Dorminhoco gigante.", favorito: false },
{ id: "144", nome: "Articuno", tipo: ["Gelo","Voador"], descricao: "Ave lendária do gelo.", favorito: false },
{ id: "145", nome: "Zapdos", tipo: ["Eletrico","Voador"], descricao: "Ave lendária elétrica.", favorito: false },
{ id: "146", nome: "Moltres", tipo: ["Fogo","Voador"], descricao: "Ave lendária de fogo.", favorito: false },
{ id: "147", nome: "Dratini", tipo: ["Dragao"], descricao: "Pequeno dragão.", favorito: false },
{ id: "148", nome: "Dragonair", tipo: ["Dragao"], descricao: "Corpo elegante.", favorito: false },
{ id: "149", nome: "Dragonite", tipo: ["Dragao","Voador"], descricao: "Muito poderoso.", favorito: false },
{ id: "150", nome: "Mewtwo", tipo: ["Psiquico"], descricao: "Criado geneticamente.", favorito: false },
{ id: "151", nome: "Mew", tipo: ["Psiquico"], descricao: "Extremamente raro.", favorito: false },
];